[2021-07-17 13:58:05,794] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-05-16T00:00:00+00:00 [queued]>
[2021-07-17 13:58:05,805] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-05-16T00:00:00+00:00 [queued]>
[2021-07-17 13:58:05,807] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-17 13:58:05,807] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-07-17 13:58:05,807] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-17 13:58:05,848] {taskinstance.py:1107} INFO - Executing <Task(HttpSensor): is_api_available> on 2020-05-16T00:00:00+00:00
[2021-07-17 13:58:05,854] {standard_task_runner.py:52} INFO - Started process 8442 to run task
[2021-07-17 13:58:05,869] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', '2020-05-16T00:00:00+00:00', '--job-id', '697', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp78wh9ixi', '--error-file', '/tmp/tmprxwb_49y']
[2021-07-17 13:58:05,870] {standard_task_runner.py:77} INFO - Job 697: Subtask is_api_available
[2021-07-17 13:58:05,962] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.is_api_available 2020-05-16T00:00:00+00:00 [running]> on host 120364900fc4
[2021-07-17 13:58:06,091] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2020-05-16T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-05-16T00:00:00+00:00
[2021-07-17 13:58:06,093] {http.py:101} INFO - Poking: api/
[2021-07-17 13:58:06,119] {base.py:78} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: {}
[2021-07-17 13:58:06,121] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2021-07-17 13:58:06,634] {base.py:248} INFO - Success criteria met. Exiting.
[2021-07-17 13:58:06,642] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20200516T000000, start_date=20210717T135805, end_date=20210717T135806
[2021-07-17 13:58:06,683] {local_task_job.py:151} INFO - Task exited with return code 1
