[2021-07-17 13:56:36,675] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-04-03T00:00:00+00:00 [queued]>
[2021-07-17 13:56:36,703] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-04-03T00:00:00+00:00 [queued]>
[2021-07-17 13:56:36,703] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-17 13:56:36,703] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-07-17 13:56:36,703] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-17 13:56:36,738] {taskinstance.py:1107} INFO - Executing <Task(HttpSensor): is_api_available> on 2020-04-03T00:00:00+00:00
[2021-07-17 13:56:36,747] {standard_task_runner.py:52} INFO - Started process 7714 to run task
[2021-07-17 13:56:36,770] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', '2020-04-03T00:00:00+00:00', '--job-id', '476', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmphpltes28', '--error-file', '/tmp/tmp9u63baz0']
[2021-07-17 13:56:36,770] {standard_task_runner.py:77} INFO - Job 476: Subtask is_api_available
[2021-07-17 13:56:36,919] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.is_api_available 2020-04-03T00:00:00+00:00 [running]> on host 120364900fc4
[2021-07-17 13:56:37,097] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2020-04-03T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-04-03T00:00:00+00:00
[2021-07-17 13:56:37,097] {http.py:101} INFO - Poking: api/
[2021-07-17 13:56:37,122] {base.py:78} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: {}
[2021-07-17 13:56:37,123] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2021-07-17 13:56:37,480] {base.py:248} INFO - Success criteria met. Exiting.
[2021-07-17 13:56:37,519] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20200403T000000, start_date=20210717T135636, end_date=20210717T135637
[2021-07-17 13:56:37,622] {local_task_job.py:151} INFO - Task exited with return code 1
