[2021-07-17 13:56:08,163] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-03-08T00:00:00+00:00 [queued]>
[2021-07-17 13:56:08,172] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-03-08T00:00:00+00:00 [queued]>
[2021-07-17 13:56:08,173] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-17 13:56:08,173] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-07-17 13:56:08,174] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-17 13:56:08,229] {taskinstance.py:1107} INFO - Executing <Task(HttpSensor): is_api_available> on 2020-03-08T00:00:00+00:00
[2021-07-17 13:56:08,233] {standard_task_runner.py:52} INFO - Started process 7403 to run task
[2021-07-17 13:56:08,241] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', '2020-03-08T00:00:00+00:00', '--job-id', '365', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpo3c8nkvo', '--error-file', '/tmp/tmptgcn4yin']
[2021-07-17 13:56:08,242] {standard_task_runner.py:77} INFO - Job 365: Subtask is_api_available
[2021-07-17 13:56:08,301] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.is_api_available 2020-03-08T00:00:00+00:00 [running]> on host 120364900fc4
[2021-07-17 13:56:08,360] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2020-03-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-03-08T00:00:00+00:00
[2021-07-17 13:56:08,362] {http.py:101} INFO - Poking: api/
[2021-07-17 13:56:08,373] {base.py:78} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: {}
[2021-07-17 13:56:08,375] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2021-07-17 13:56:08,694] {base.py:248} INFO - Success criteria met. Exiting.
[2021-07-17 13:56:08,712] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20200308T000000, start_date=20210717T135608, end_date=20210717T135608
[2021-07-17 13:56:08,770] {local_task_job.py:151} INFO - Task exited with return code 1
