[2021-07-17 13:57:35,436] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-05-01T00:00:00+00:00 [queued]>
[2021-07-17 13:57:35,447] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-05-01T00:00:00+00:00 [queued]>
[2021-07-17 13:57:35,448] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-17 13:57:35,448] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-07-17 13:57:35,449] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-17 13:57:35,484] {taskinstance.py:1107} INFO - Executing <Task(HttpSensor): is_api_available> on 2020-05-01T00:00:00+00:00
[2021-07-17 13:57:35,489] {standard_task_runner.py:52} INFO - Started process 8188 to run task
[2021-07-17 13:57:35,495] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', '2020-05-01T00:00:00+00:00', '--job-id', '621', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpoq0k5fnw', '--error-file', '/tmp/tmpe2gwycrz']
[2021-07-17 13:57:35,496] {standard_task_runner.py:77} INFO - Job 621: Subtask is_api_available
[2021-07-17 13:57:35,538] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.is_api_available 2020-05-01T00:00:00+00:00 [running]> on host 120364900fc4
[2021-07-17 13:57:35,656] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2020-05-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-05-01T00:00:00+00:00
[2021-07-17 13:57:35,657] {http.py:101} INFO - Poking: api/
[2021-07-17 13:57:35,672] {base.py:78} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: {}
[2021-07-17 13:57:35,675] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2021-07-17 13:57:35,992] {base.py:248} INFO - Success criteria met. Exiting.
[2021-07-17 13:57:36,009] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20200501T000000, start_date=20210717T135735, end_date=20210717T135736
[2021-07-17 13:57:36,076] {local_task_job.py:151} INFO - Task exited with return code 1
